name: Selenium Test Automation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Bước 3: Cài đặt các dependencies cần thiết
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y maven wget curl unzip

      # Bước 4: Cài đặt phiên bản Google Chrome mới nhất
      - name: Install latest Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt --fix-broken install -y

      # Bước 5: Kiểm tra Chrome đã được cài đặt thành công
      - name: Verify Chrome installation
        run: |
          google-chrome-stable --version || (echo "Chrome installation failed" && exit 1)

      # Bước 6: Cài đặt ChromeDriver tương thích
      - name: Install ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome-stable --version | awk '{print $3}' | cut -d '.' -f1,2)
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION" || echo "Not Found")
          if [ "$CHROMEDRIVER_VERSION" == "Not Found" ]; then
            echo "ChromeDriver for Chrome version $CHROME_VERSION is not available."
            exit 1
          fi
          echo "Installing ChromeDriver version: $CHROMEDRIVER_VERSION"
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          chmod +x /usr/local/bin/chromedriver

      # Bước 7: Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Bước 8: Chạy các bài kiểm tra Selenium
      - name: Run Selenium Tests
        run: mvn clean test
