name: Selenium Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Cài đặt JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      # Bước 3: Cài đặt các dependencies cần thiết
      - name: Install dependencies
        run: |
          choco install maven

      # Bước 4: Tải và giải nén Google Chrome Portable từ file .zip
      - name: Install Google Chrome Portable from ZIP
        run: |
          # Tải Google Chrome Portable từ GitHub repository
          Invoke-WebRequest -Uri "https://github.com/TungSyo/Aumation_AFF/raw/main/chrome-files/GoogleChromePortable.zip" -OutFile "GoogleChromePortable.zip"
          # Giải nén file ZIP vào thư mục mong muốn (ví dụ D:\Zalo\DATN\File_DATN)
          Expand-Archive -Path "GoogleChromePortable.zip" -DestinationPath "D:\Zalo\DATN\File_DATN"
          # Di chuyển thư mục chứa Google Chrome Portable vào thư mục đích
          Move-Item -Path "D:\Zalo\DATN\File_DATN\GoogleChromePortable" -Destination "D:\Zalo\DATN\File_DATN\Google Chrome Portable"

      # Bước 5: Cài đặt ChromeDriver từ file .exe
      - name: Install ChromeDriver
        run: |
          # Tải ChromeDriver từ GitHub repository
          Invoke-WebRequest -Uri "https://github.com/TungSyo/Aumation_AFF/raw/main/chrome-files/chromedriver.exe" -OutFile "chromedriver.exe"
          # Di chuyển chromedriver.exe vào thư mục hệ thống để Selenium có thể tìm thấy
          Move-Item -Path "chromedriver.exe" -Destination "D:\Zalo\DATN\File_DATN\ChromeDriver"

      # Bước 6: Chạy các bài kiểm tra Selenium
      - name: Run Selenium Tests
        run: mvn clean test
